feat: createfs also support linux

diff --git a/createfs b/createfs
--- a/createfs
+++ b/createfs
@@ -8,17 +8,54 @@ VOLUME_NAME="REDOS"
 [ -f "$IMG" ] && rm "$IMG"
 [ -f "$IMG.dmg" ] && rm "$IMG.dmg"
 
-DEV_INFO=$(hdiutil create -size ${SIZE_MB}m -fs "ExFAT" -layout NONE -volname "$VOLUME_NAME" "$IMG" -attach)
-MOUNTPOINT=$(echo "$DEV_INFO" | awk '/\/Volumes\// {print $NF}')
-DEVICE=$(echo "$DEV_INFO" | awk '/\/dev\/disk/ {print $1; exit}')
+function need_executable() {
 
-cp -R "$FOLDER/" "$MOUNTPOINT/"
+    EXECUTABLE="$1"
 
-#.fseventsd is not getting deleted i think
-find "$MOUNTPOINT/" -type f \( -name '.DS_Store' -o -name '.fseventsd' -o -name '._*' \) -delete
+    RECOMMENDED_PACKAGE="$2"
 
-echo "$MOUNTPOINT"
-echo "DEV: $DEVICE"
+    if ! command -v "$EXECUTABLE" >/dev/null 2>&1; then
+        echo "Error: this script needs the '$EXECUTABLE' executable, please install it" >&2
+        if [ -n "$RECOMMENDED_PACKAGE" ]; then
+            echo "The recommended package to install for this program is: '$RECOMMENDED_PACKAGE'" >&2
+        fi
+        exit 1
+    fi
 
-hdiutil detach "$DEVICE"
-mv "$IMG.dmg" "$IMG"
+}
+
+OS_TYPE="$(uname)"
+
+if [[ "$OS_TYPE" == "Darwin" ]]; then
+    echo "Running on macOS"
+    need_executable hdiutil
+
+    DEV_INFO=$(hdiutil create -size ${SIZE_MB}m -fs "ExFAT" -layout NONE -volname "$VOLUME_NAME" "$IMG" -attach)
+    MOUNTPOINT=$(echo "$DEV_INFO" | awk '/\/Volumes\// {print $NF}')
+    DEVICE=$(echo "$DEV_INFO" | awk '/\/dev\/disk/ {print $1; exit}')
+
+    cp -R "$FOLDER/" "$MOUNTPOINT/"
+
+    #.fseventsd is not getting deleted i think
+    find "$MOUNTPOINT/" -type f \( -name '.DS_Store' -o -name '.fseventsd' -o -name '._*' \) -delete
+
+    echo "$MOUNTPOINT"
+    echo "DEV: $DEVICE"
+
+    hdiutil detach "$DEVICE"
+    mv "$IMG.dmg" "$IMG"
+
+elif [[ "$OS_TYPE" == "Linux" ]]; then
+    echo "Running on Linux"
+
+    need_executable dd
+    need_executable mkfs.exfat "exfatprogs"
+
+    # 1. Create an empty image file
+    dd if=/dev/zero of="$IMG" bs=1M count="$SIZE_MB"
+
+    # 2. Format it as ExFAT
+    mkfs.exfat -n "$VOLUME_NAME" "$IMG"
+else
+    echo "Unknown OS: $OS_TYPE"
+fi
